function m(b,a,c,d){b.m.mb(b.qb,a,c,d)}function n(b,a,c,d){b.m.ba?m(b,a,c,d):b.m.Te()._OnMessageFromDOM({type:"event",component:b.qb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function aa(b,a,c){b.m.B(b.qb,a,c)}function ba(b,a){for(const [c,d]of a)aa(b,c,d)}function q(b){b.Ub||(b.m.Cc(b.ie),b.Ub=!0)}window.rc=class{constructor(b,a){this.m=b;this.qb=a;this.Ub=!1;this.ie=()=>this.Oa()}qd(){}Oa(){}};
window.Ef=class{constructor(){this.ld=-1}j(){-1!==this.ld&&(self.clearTimeout(this.ld),this.ld=-1)}};"use strict";class ca{constructor(b){this.tb=b;this.Sc=!1;this.Zc=!0;this.vb=this.pa=this.md=-1}}
function da(b,a){const c=a.elementId,d=b.ud(c,a),e=new ca(d);b.Ha.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Zc=!!a.isVisible;var f=b.Fc(d);f.addEventListener("focus",()=>{ea(b,"elem-focused",c)});f.addEventListener("blur",()=>{ea(b,"elem-blurred",c)});f=a.htmlIndex;e.md=f;e.vb=a.htmlZIndex;b.Ra&&(a=b.m.sc(f),e.pa=a,b.m.gb(a).appendChild(d))}function fa(b,a){aa(b,"get-element",c=>{const d=v(b,c.elementId);return a(d,c)})}
function v(b,a){b=b.Ha.get(a);if(!b)throw Error(`no element with id ${a}`);return b.tb}function ea(b,a,c){var d;d||(d={});d.elementId=c;m(b,a,d)}
window.qc=class extends self.rc{constructor(b){super(b,"button");this.Ha=new Map;this.Ra=!0;ba(this,[["create",a=>da(this,a)],["destroy",a=>{a=a.elementId;const c=v(this,a);this.Ra&&c.parentElement.removeChild(c);this.Ha.delete(a)}],["set-visible",a=>{if(this.Ra){var c=this.Ha.get(a.elementId),d=c.tb;c.Sc?d.style.display=a.isVisible?"":"none":c.Zc=!!a.isVisible}}],["update-position",a=>{if(this.Ra){var c=this.Ha.get(a.elementId),d=c.tb,e=this.m;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";var f=a.fontSize;null!==f&&(d.style.fontSize=f+"em");f=a.htmlIndex;c.md=f;f=e.sc(f);f!==c.pa&&(d.remove(),e.gb(f).appendChild(d),c.pa=f,e.Mc());a=a.htmlZIndex;a!==c.vb&&(c.vb=a,e.Mc());c.Sc||(c.Sc=!0,c.Zc&&(d.style.display=""))}}],["update-state",a=>{const c=v(this,a.elementId);this.Bc(c,a)}],["focus",a=>{const c=this.Fc(v(this,a.elementId));a.focus?c.focus():c.blur()}],["set-css-style",a=>{const c=v(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,
a):c.style[d]=a}],["set-attribute",a=>{v(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{v(this,a.elementId).removeAttribute(a.name)}]]);fa(this,a=>a)}ud(){throw Error("required override");}Bc(){throw Error("required override");}Fc(b){return b}};"use strict";const ha=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),w=/android/i.test(navigator.userAgent),ia=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);
let ja=0;function x(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.uf?new Promise(c=>{const d="c3_resolve_"+ja;++ja;self[d]=c;a.textContent=b.yf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function na(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let y=new Audio;
const oa={"audio/webm; codecs=opus":!!y.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!y.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!y.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!y.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!y.canPlayType("audio/mp4"),"audio/mpeg":!!y.canPlayType("audio/mpeg")};y=null;async function pa(b){b=await qa(b);return(new TextDecoder("utf-8")).decode(b)}
function qa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const z=[];let A=0;window.RealFile=window.File;const B=[],D=new Map,E=new Map;let ra=0;const sa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");sa.push(b)};const ta=new Set(["cordova","playable-ad","instant-games"]);let ua=!1;
window.Mb=class b{constructor(a){this.ba=a.Af;this.xa=null;this.aa="";this.ab=a.xf;this.Ib={};this.Va=this.ua=null;this.Ta=[];this.ma=null;this.Wd=!0;this.M=[];this.ed=[];this.fd=!1;this.je=()=>this.Re();this.Wc=!1;this.Qd=0;this.xb=null;this.$a=-1;this.qf=()=>this.bf();this.Fb=new Set;this.nd=null;this.ke=[];this.A=a.le;this.Vb="file"===location.protocol.substr(0,4);if("playable-ad"===this.A||"instant-games"===this.A)this.ba=!1;ia&&(this.ba=!1);if("cordova"===this.A&&this.ba&&w){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ba=!1)}this.Ma()?self.chrome.webview.addEventListener("message",c=>this.Fd(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.Fd(c));this.Yb=this.ra=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.ff(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Xe());this.B("runtime","cordova-fetch-local-file",c=>this.Ye(c));this.B("runtime","create-job-worker",()=>this.Ze());this.B("runtime","send-wrapper-extension-message",c=>this.ef(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.Dd(a)):this.Dd(a)}j(){this.Dc();this.xa&&(this.xa=this.xa.onmessage=null);this.ua&&(this.ua.terminate(),this.ua=null);this.Va&&(this.Va.j(),this.Va=null);for(const {canvas:a,
eb:c}of this.M)a.remove(),c.remove();this.M.length=0}De(){return this.M[0].canvas}sc(a){return Math.min(a,this.M.length-1)}gb(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].eb}_GetHTMLWrapElement(a){return this.gb(a)}He(){return ha&&"cordova"===this.A}kb(){const a=navigator.userAgent;return ha&&ta.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Fe(){return w}wd(){return w&&ta.has(this.A)}yd(){return"windows-webview2"===this.A||!!("preview"===
this.A&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}Ma(){return this.yd()||"xbox-uwp-webview2"===this.A}async Dd(a){this.ba&&!await na()&&(this.ba=!1);"macos-wkwebview"===this.A?this.nb({type:"ready"}):this.Ma()&&(this.hf(),this.ke=(await this.We()).registeredComponentIds);if("playable-ad"===this.A){this.ra=self.c3_base64files;this.Yb={};await this.Oe();for(let d=0,e=a.cb.length;d<e;++d){var c=a.cb[d];this.Yb.hasOwnProperty(c)?a.cb[d]={uf:!0,yf:this.Yb[c]}:this.ra.hasOwnProperty(c)&&
(a.cb[d]=URL.createObjectURL(this.ra[c]))}a.mc=[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Cc(()=>{d++;document.documentElement.style.opacity=0===d%2?"1":"0.999"})}a.wf?this.aa=a.wf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Cf&&(this.Ib=a.Cf);c=new MessageChannel;this.xa=c.port1;this.xa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&
window.c3_addPortMessageHandler(d=>this.af(d));this.xb=new self.Ie(this);await va(this.xb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ba?await this.Ve(a,c.port2):await this.Ue(a,c.port2)}Gc(a){a=this.Ib.hasOwnProperty(a)?this.Ib[a]:a.endsWith("/workermain.js")&&this.Ib.hasOwnProperty("workermain.js")?
this.Ib["workermain.js"]:"playable-ad"===this.A&&this.ra.hasOwnProperty(a)?this.ra[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async pc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Vb)return a=await this.Jb(d.tf?a:this.ab+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}oa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}uc(){return this.Ma()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.A)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}Cd(a){var c=this.aa,d=location.href,e=this.oa(),
f=this.ga(),g=this.uc(),h=window.devicePixelRatio,k=b.jb(),l=a.Hf,p=window.cr_previewImageBlobs||this.ra,r=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,u=window.cr_swClientId||"";a=a.le;var Y=(new URLSearchParams(self.location.search)).has("debug"),F=this.xb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,cssDisplayMode:g,devicePixelRatio:h,isFullscreen:k,projectData:l,previewImageBlobs:p,previewProjectFileBlobs:r,previewProjectFileSWUrls:t,swClientId:u,
exportType:a,isDebug:Y,ife:!!self.Gf,jobScheduler:{inputPort:F.Vc,outputPort:F.dd,maxNumWorkers:F.mf},supportedAudioFormats:oa,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ab+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ab+"opus.wasm.wasm",isFileProtocol:this.Vb,isiOSCordova:this.He(),isiOSWebView:this.kb(),isWindowsWebView2:this.yd(),isAnyWebView2Wrapper:this.Ma(),wrapperComponentIds:this.ke,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ve(a,c){const d=
this.Gc(a.Bf);"preview"===this.A?(this.ua=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.ua.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.ua.addEventListener("message",r);this.ua.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.ua=await this.pc(d,this.aa,{type:"module",name:"Runtime",tf:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();
document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,eb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.mc||[],k=a.cb;h=await Promise.all(h.map(l=>this.Pa(l)));k=await Promise.all(k.map(l=>this.Pa(l)));if("cordova"===this.A)for(let l=0,p=a.lc.length;l<p;++l){const r=a.lc[l],t=r[0];if(t===a.od||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Pa(t)}this.ua.postMessage(Object.assign(this.Cd(a),
{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.lc,mainProjectScript:a.od,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...wa(this.xb)]);this.Ta=B.map(l=>new l(this));this.Bd();G(e);xa(g);ya(this.ma);self.c3_callFunction=(l,p)=>{var r=this.ma;return r.m.zd(r.qb,"js-invoke-function",{name:l,params:p})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.mb("runtime","go-to-last-error-script"))}async Ue(a,c){const d=
document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,eb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ta=B.map(h=>new h(this));this.Bd();G(d);xa(e);e=a.cb.map(h=>"string"===typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.mc)){var f=[...a.mc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=
await Promise.all(e.map(h=>this.Pa(h)));await Promise.all(e.map(h=>x(h)));e=self.C3_ProjectScriptsStatus;f=a.od;const g=a.lc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Pa(k),await x(k),"preview"!==this.A||e[h]||this.Hd(h,"main script did not run to completion")}catch(l){this.Hd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=await this.Pa(k),await x(k);"preview"===this.A&&"object"!==typeof self.Df.Ff?(this.Pb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Cd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:sa}),ya(this.ma),this.Ed(),this.Va=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Va,a))}Hd(a,c){this.Pb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ed(){this.Pb()}Pb(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ze(){const a=await za(this.xb);return{outputPort:a,transferables:[a]}}ff(a){if(!this.Wc){var c=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,eb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Wd&&(g.style.display="",h.style.display=
"");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Wd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,eb:p}=this.M.pop();p.remove();this.ba&&!d?this.ed.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),
this.ba?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,G(c),xa(d),this.M.push({canvas:c,eb:d});for(const l of this.Ta)if(l instanceof window.qc&&l.Ra)for(const p of l.Ha.values())e=l.m.sc(p.md),f=p.pa,-1!==
e&&-1!==f&&e!==f&&(f=p.tb,f.remove(),l.m.gb(e).appendChild(f),p.pa=e);this.Mc();return{addedCanvases:a,transferables:k}}Xe(){for(const a of this.ed)a.remove();this.ed.length=0}Mc(){this.fd||(this.fd=!0,this.Cc(this.je))}Re(){this.Gd(this.je);this.fd=!1;let a=[];for(var c of this.Ta)if(c instanceof window.qc){var d=c.Ra?[...c.Ha.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.pa,l=h.pa;return k!==l?k-l:g.vb-h.vb});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.pa!==c&&(this.Ad(c,a.slice(d,
e)),c=g.pa,d=e)}d<e&&this.Ad(c,a.slice(d,e))}Ad(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.tb);var d=new Set(c);a=this.gb(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Te(){if(this.ba)throw Error("not available in worker mode");return this.Va}mb(a,c,d,e,f){this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}zd(a,c,d,e,f){const g=ra++,h=new Promise((k,l)=>{E.set(g,{resolve:k,reject:l})});this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.$e(a);if("result"===c)this.cf(a);else if("runtime-ready"===c)this.df();else if("alert-error"===c)this.Pb(),alert(a.message);else if("creating-runtime"===c)this.Ed();else throw Error(`unknown message '${c}'`);}$e(a){const c=a.component,d=a.handler,
e=a.data,f=a.responseId;if(a=D.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Ob(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Ob(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Ob(f,!1,""+h)}):this.Ob(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Ob(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.xa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}cf(a){const c=a.responseId,d=a.isOk;a=a.result;const e=E.get(c);d?e.resolve(a):e.reject(a);E.delete(c)}B(a,c,d){let e=D.get(a);e||(e=new Map,D.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static nc(a){if(B.includes(a))throw Error("DOM handler already added");B.push(a)}Bd(){for(const a of this.Ta)if("runtime"===a.qb){this.ma=a;return}throw Error("cannot find runtime DOM handler");
}af(a){this.mb("debugger","message",a)}df(){for(const a of this.Ta)a.qd()}static jb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ua)}static Id(a){ua=!!a}Cc(a){this.Fb.add(a);this.Lc()}Gd(a){this.Fb.delete(a);0===this.Fb.size&&this.Dc()}Lc(){-1===this.$a&&0<this.Fb.size&&(this.$a=requestAnimationFrame(this.qf))}Dc(){-1!==this.$a&&(cancelAnimationFrame(this.$a),this.$a=-1)}bf(){this.$a=-1;for(const a of this.Fb)a();this.Lc()}Da(a){this.ma.Da(a)}Na(a){this.ma.Na(a)}Kc(){this.ma.Kc()}Nb(a){this.ma.Nb(a)}Ge(){return!!oa["audio/webm; codecs=opus"]}async jf(a){a=
await this.zd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ke(a){this.Wc=!0;this.Qd=a}Ee(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}xd(a){return!this.Ee(a)}async Pa(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Vb&&this.xd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Jb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ye(a){const c=a.filename;switch(a.as){case "text":return await this.Ce(c);
case "buffer":return await this.Jb(c);default:throw Error("unsupported type");}}td(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Ce(a){a=await this.td(a);return await pa(a)}Ec(){if(z.length&&!(8<=A)){A++;var a=z.shift();this.Pe(a.filename,a.zf,a.sf)}}Jb(a){return new Promise((c,d)=>{z.push({filename:a,zf:e=>{A--;this.Ec();c(e)},sf:e=>{A--;this.Ec();d(e)}});this.Ec()})}async Pe(a,c,d){try{const e=
await this.td(a),f=await qa(e);c(f)}catch(e){d(e)}}Fd(a){if("entered-fullscreen"===a)b.Id(!0),H(this.ma);else if("exited-fullscreen"===a)b.Id(!1),H(this.ma);else if("object"===typeof a){const c=a.type;"directory-handles"!==c&&("wrapper-init-response"===c?(this.nd(a),this.nd=null):"extension-message"===c?this.mb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a))}else console.warn("Unknown wrapper message: ",a)}ef(a){this.nb({type:"extension-message",componentId:a.componentId,
messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}nb(a){this.Ma()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}hf(){window.moveTo=(a,c)=>{this.nb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.nb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}We(){return this.Ma()?new Promise(a=>{this.nd=a;this.nb({type:"wrapper-init"})}):
Promise.resolve()}async Oe(){const a=[];for(const [c,d]of Object.entries(this.ra))a.push(this.Ne(c,d));await Promise.all(a)}async Ne(a,c){if("object"===typeof c)this.ra[a]=new Blob([c.str],{type:c.type}),this.Yb[a]=c.str;else{let d=await this.Se(c);d||(d=this.Qe(c));this.ra[a]=d}}async Se(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Qe(a){a=this.gf(a);return this.Me(a.data,a.vf)}gf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{vf:a,data:d}}Me(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const I=self.Mb,Aa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ba={dispatchUserScriptEvent:!0},Ca={dispatchRuntimeEvent:!0};function Da(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}
function Ea(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function Fa(b){b=URL.createObjectURL(b);try{return await Ea(b)}finally{URL.revokeObjectURL(b)}}function Ga(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ha=new Set(["input","textarea","datalist","select"]),Ia=new Set(["canvas","body","html"]);
function K(b){b.target.tagName&&Ia.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ja(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Ka(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await Fa(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Fa(b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let La=!1;document.addEventListener("pause",()=>La=!0);document.addEventListener("resume",()=>La=!1);function G(b){b.addEventListener("selectstart",K);b.addEventListener("gesturehold",K);b.addEventListener("pointerdown",K)}function xa(b){b.addEventListener("selectstart",Ja);b.addEventListener("gesturehold",Ja);b.addEventListener("touchstart",Ja)}function ya(b){b.Pd=!0;b.$c=b.m.oa();b.yb=b.m.ga()}
function H(b){if(!b.ka){var a=I.jb();a&&"any"!==b.jd&&Ma(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ga()})}}async function Na(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Oa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Pa(b){return await self.C3_GetSvgImageSize(b.blob)}function Qa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ra(b){self.setTimeout(()=>{b.Od=!0},1E3);"cordova"===b.m.A?(document.addEventListener("pause",()=>Sa(b,!0)),document.addEventListener("resume",()=>Sa(b,!1))):document.addEventListener("visibilitychange",()=>Sa(b,"hidden"===document.visibilityState));b.bc=!("hidden"!==document.visibilityState&&!La);return{isSuspended:b.bc}}
function Ta(b){b.Kd||(b.Kd=!0,window.addEventListener("deviceorientation",a=>{b.ka||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.ka||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Ua(b){b.Jd||(b.Jd=!0,window.addEventListener("devicemotion",a=>{if(!b.ka){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Va(b){await Da(b.url)}
function Wa(b,a){b.Rd=a.message;-1===b.Qc&&(b.Qc=setTimeout(()=>{b.Qc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Rd)},250))}function Xa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:I.jb(),innerWidth:b.oa(),innerHeight:b.ga()})}
function Sa(b,a){b.bc!==a&&((b.bc=a)?b.m.Dc():b.m.Lc(),m(b,"visibilitychange",{hidden:a}),!a&&b.m.kb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Ya(b,a,c){"Backspace"===c.key&&K(c);"nwjs"===b.m.A&&"u"===c.key&&(c.ctrlKey||c.metaKey)&&c.preventDefault();if(!b.ka){var d=Aa.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},J)}}
function L(b,a,c,d){b.ka||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Aa,pageX:c.pageX,pageY:c.pageY+b.Aa,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function M(b,a,c){if(!b.ka){var d=0;"mouse"===c.pointerType&&(d=b.bd);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Aa,pageX:c.pageX,pageY:c.pageY+b.Aa,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},J);"mouse"===c.pointerType&&
(b.bd=c.buttons)}}function Za(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Aa=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Aa=a))}}
function $a(b,a,c,d){const e=b.oa(),f=b.ga();b.bb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.jb(),cssDisplayMode:b.m.uc()}):10>d&&ab(b,e,f,d+1)}function ab(b,a,c,d){-1!==b.bb&&clearTimeout(b.bb);b.bb=setTimeout(()=>$a(b,a,c,d),48)}
function Ma(b){b=b.jd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function bb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.nc(class extends self.rc{constructor(b){super(b,"runtime");this.Pd=!1;this.bb=-1;this.jd="any";this.bc=this.Jd=this.Kd=!1;this.ic=document.createElement("div");this.ic.className="c3-screen-reader-text";this.ic.setAttribute("aria-live","polite");document.body.appendChild(this.ic);this.Ga=null;this.ka=!1;this.Rd="";this.Qc=-1;this.Od=!1;this.$c=b.oa();this.yb=b.ga();this.Aa=this.Hb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Na(c));b.B("runtime","raster-svg-image",c=>Oa(c));b.B("runtime","get-svg-image-size",c=>Pa(c));b.B("runtime","set-target-orientation",c=>{this.jd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Qa(c));b.B("runtime","go-to-script",c=>Qa(c));b.B("runtime","before-start-ticking",()=>Ra(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ga||(this.Ga=document.createElement("div"),this.Ga.id="inspectOutline",document.body.appendChild(this.Ga));var d=this.Ga;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ga&&(this.Ga.style.display="none")});b.B("runtime","enable-device-orientation",()=>Ta(this));b.B("runtime","enable-device-motion",()=>Ua(this));b.B("runtime","add-stylesheet",c=>Va(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>{alert(c.message)});b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.ic.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===
d?(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ka=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.m.De().style.display="";this.m.Ke(c.duration)});b.B("runtime","export-to-video-progress",c=>Wa(this,c));b.B("runtime","exported-to-video",c=>{window.rf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.rf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ga(d)||c.preventDefault()});window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);window.addEventListener("touchstart",K,{passive:!1});window.addEventListener("pointerdown",K,{passive:!1});this.bd=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ka,{passive:!1});window.addEventListener("wheel",Ka,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ka&&this.Pd){var c=this.oa();var d=this.ga();if(this.m.wd()){if(this.Od){if(this.$c===
c&&d<this.yb){this.Hb=this.yb-d;Za(this,this.yb,this.Hb);c=void 0;break a}0<this.Hb&&(this.Hb=0,Za(this,d,this.Hb))}this.$c=c;this.yb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.jb(),cssDisplayMode:this.m.uc()});this.m.kb()&&(-1!==this.bb&&clearTimeout(this.bb),$a(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",
()=>H(this));window.addEventListener("fullscreenerror",c=>Xa(this,c));window.addEventListener("webkitfullscreenerror",c=>Xa(this,c));window.addEventListener("mozfullscreenerror",c=>Xa(this,c));if(b.kb()){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d});document.documentElement.setAttribute("ioswebview","")}this.Wa=new Set;this.$b=new WeakSet;this.wa=!1}qd(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,Ca)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}m(this,"window-blur",{parentHasFocus:a},Ca);this.bd=0});window.addEventListener("focusin",a=>{a=a.target;(Ha.has(a.tagName.toLowerCase())||Ga(a))&&m(this,"keyboard-blur",null,Ca)});window.addEventListener("keydown",a=>Ya(this,"keydown",a));window.addEventListener("keyup",a=>Ya(this,"keyup",a));window.addEventListener("mousedown",a=>L(this,"mousedown",a,
Ba));window.addEventListener("mousemove",a=>L(this,"mousemove",a,Ba));window.addEventListener("mouseup",a=>L(this,"mouseup",a,Ba));window.addEventListener("dblclick",a=>L(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.ka||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Aa,pageX:a.pageX,pageY:a.pageY+this.Aa,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();
bb(a.target)&&document.activeElement&&!bb(document.activeElement)&&document.activeElement.blur();M(this,"pointerdown",a)});this.m.ba&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{M(this,"pointermove",a)}):window.addEventListener("pointermove",a=>M(this,"pointermove",a));window.addEventListener("pointerup",a=>M(this,"pointerup",a));window.addEventListener("pointercancel",a=>M(this,"pointercancel",a));const b=()=>this.Kc();window.addEventListener("pointerup",
b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.m.Fe()&&!this.m.wd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Za(this,this.ga(),navigator.virtualKeyboard.boundingRect.height)}));this.m.kb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}oa(){return this.m.oa()}ga(){return this.m.ga()}Kc(){var b=
[...this.Wa];this.Wa.clear();if(!this.wa)for(const a of b)(b=a.play())&&b.catch(()=>{this.$b.has(a)||this.Wa.add(a)})}Da(b){if("function"!==typeof b.play)throw Error("missing play function");this.$b.delete(b);let a;try{a=b.play()}catch(c){this.Wa.add(b);return}a&&a.catch(()=>{this.$b.has(b)||this.Wa.add(b)})}Na(b){this.Wa.delete(b);this.$b.add(b)}Nb(b){this.wa=!!b}});"use strict";
async function va(b){if(b.kf)throw Error("already initialised");b.kf=!0;var a=b.ya.Gc(("playable-ad"===b.ya.A?b.ya.ab:"")+"dispatchworker.js");b.Pc=await b.ya.pc(a,b.pb,{name:"DispatchWorker"});a=new MessageChannel;b.Vc=a.port1;b.Pc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.dd=await za(b)}function wa(b){return[b.Vc,b.dd]}
async function za(b){const a=b.Xd.length;var c=b.ya.Gc(("playable-ad"===b.ya.A?b.ya.ab:"")+"jobworker.js");c=await b.ya.pc(c,b.pb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Pc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Xd.push(c);return e.port1}
self.Ie=class{constructor(b){this.ya=b;this.pb=b.aa;this.pb="preview"===b.A?this.pb+"workers/":this.pb+b.ab;this.mf=Math.min(navigator.hardwareConcurrency||2,16);this.Pc=null;this.Xd=[];this.dd=this.Vc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.Mb({Af:!0,Bf:"workermain.js",cb:["scripts/c3runtime.js"],lc:[],od:"",xf:"scripts/",mc:[],le:"html5"}));"use strict";function N(b){b.stopPropagation()}
self.Mb.nc(class extends self.qc{constructor(b){super(b)}ud(b,a){const c=document.createElement("input");var d=c;a.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",N);d.addEventListener("pointermove",N);d.addEventListener("pointerrawupdate",
N);d.addEventListener("pointerup",N);d.addEventListener("mousedown",N);d.addEventListener("mouseup",N);d.addEventListener("keydown",N);d.addEventListener("keyup",N);d.addEventListener("contextmenu",e=>e.preventDefault());c.addEventListener("click",()=>{var e={isChecked:c.checked};e.elementId=b;n(this,"click",e)});a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.Bc(d,a);return d}Fc(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}Bc(b,a){const c="input"===b.tagName.toLowerCase()?
b:b.firstChild;c.checked=a.isChecked;c.disabled=!a.isEnabled;b.title=a.title;b===c?c.value=a.text:b.lastChild.textContent=a.text}});"use strict";const cb=180/Math.PI;
async function db(b,a){a.usePlayMusicAsSoundWorkaround&&(b.dc=!0);b.kd=a.timeScaleMode;b.be=["equalpower","HRTF","soundfield"][a.panningModel];b.Nd=["linear","inverse","exponential"][a.distanceModel];b.ce=a.refDistance;b.ae=a.maxDistance;b.ee=a.rolloffFactor;if(b.m.Wc)b.dc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.m.Qd)});else{var c={latencyHint:a.latencyHint};b.he||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");eb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&eb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Sa=b.g.createGain();b.Sa.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ca);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>O(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function gb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Yd=g.slice(0);hb(b,g);try{b.R=await ib(b,c,d,e,g,f);if(p){P(b.R,!0);var u=b.R,Y=p.x,F=p.y,wb=p.z,xb=p.angle,ka=p.innerAngle,la=p.outerAngle,ma=p.outerGain;if(u.wb){jb(u,Y,F,wb,xb);var C=self.fb.Le;
u.sa[0]!==C(ka)&&(u.sa[0]=C(ka),u.F.coneInnerAngle=C(ka));u.sa[1]!==C(la)&&(u.sa[1]=C(la),u.F.coneOuterAngle=C(la));u.sa[2]!==ma&&(u.sa[2]=ma,u.F.coneOuterGain=ma)}p.hasOwnProperty("uid")&&(b.R.qa=p.uid)}else"number"===typeof r&&0!==r?(Q(b.R,!0),kb(b.R,r)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,k,l,t)}catch(yb){console.error("[Construct] Audio: error starting playback: ",yb);return}finally{c=g.join(" ");d=b.Eb.get(c);if(!d)throw Error("expected pending tag");d.pd--;0===d.pd&&(d.resolve(),b.Eb.delete(c))}q(b)}
async function lb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await mb(b,c);for(const h of R(b,c))if(!h.va){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ka=d;h.Ua=g;h.ge=a}S(b)}async function nb(b,a){const c=a.tags;a=a.rate;await mb(b,c);for(const d of R(b,c))d.la!==a&&(d.la=a,d.Ea())}async function ob(b,a){const c=a.tags;a=a.pos;await mb(b,c);for(const d of R(b,c))d.yc(a)}
async function pb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await ib(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function qb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function rb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.re(b,...e);else if("delay"===c)d=new self.pe(b,...e);else if("convolution"===c){var g=d=new self.oe(b,f.ha,...e),h=a.bufferType;g.Ld=a.bufferOriginalUrl;g.Md=h}else if("flanger"===c)d=
new self.se(b,...e);else if("phaser"===c)d=new self.ue(b,...e);else if("gain"===c)d=new self.te(b,...e);else if("stereopan"===c)d=new self.we(b,...e);else if("tremolo"===c)d=new self.xe(b,...e);else if("ringmod"===c)d=new self.ve(b,...e);else if("distortion"===c)d=new self.qe(b,...e);else if("compressor"===c)d=new self.ne(b,...e);else if("analyser"===c)d=new self.me(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ja.get(h);l||(l=[],g.ja.set(h,l));d.Vd=l.length;d.hd=
h;l.push(d);sb(g,h)}tb(b)}
async function ub(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ba()&&1===c||!e.Ba()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ja.values())for(const g of f)g.j();b.ja.clear();b.jc=a.timeScale;b.Rc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ca[e]=d[e];b.g.listener.setOrientation(...b.ca)}b.wa=a.isSilent;b.m.Nb(b.wa);b.Zb=a.masterVolume;b.Sa.gain.value=
b.Zb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>rb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>vb(b,f,c)));S(b)}
async function zb(b,a){try{const c=b.g.suspend(a.time);b.Ud?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.m.mb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Ab(d)),b.Ud=!0);await c}catch(c){Ab(c)}}
function eb(b){b.Tb||(b.Uc=!1,window.addEventListener("pointerup",b.za,!0),window.addEventListener("touchend",b.za,!0),window.addEventListener("click",b.za,!0),window.addEventListener("keydown",b.za,!0),b.Tb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ia)if(g.ib()===c)return await Bb(g),g;if(f)return null;if(e&&(b.dc||b.Td)){f=0;for(let h=0,k=b.ia.length;h<k;++h)g=b.ia[h],b.ia[f]=g,g.Ba()?g.j():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.he;e&&f&&(b.Td=!0);c=!e||b.dc||f?new self.Ae(b,a,c,d,e,f):new self.ye(b,a,c,d,e);b.ia.push(c);await Bb(c);b.$d.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.$d.add(a));return c}
function Cb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Db(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.ea()}function sb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of Eb(b,a))e=f,d=c,e=e.da||e.F||e.G,e.disconnect(),e.connect(d);b.Ia&&b.ad===a&&(b.Ia.disconnect(),b.Ia.connect(c))}
function*Eb(b,a){if(a)for(const c of b.H)Cb(0<c.na.length?c.na[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Fb(b,a,c){return c?b.m.jf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Gb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.na;var c=a;for(const e of c){c=!1;for(const f of b)if(Cb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function ib(b,a,c,d,e,f){for(const g of b.H)if(g.ib()===c&&(g.oc()||f))return g.na=e,g;a=await O(b,a,c,d,f);e="html5"===a.Nc?new self.ze(a.u,a,e):new self.Be(a.u,a,e);b.H.push(e);return e}
function hb(b,a){a=a.join(" ");let c=b.Eb.get(a);if(!c){let d=null;c={pd:0,promise:new Promise(e=>d=e),resolve:d};b.Eb.set(a,c)}c.pd++}function mb(b,a){return(b=b.Eb.get((0===a.length?b.Yd:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Qa.size)q(b);else for(const a of b.H)if(!a.I&&!a.O()){q(b);break}}function Hb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function tb(b){b.Xc||(b.Xc=!0,Promise.resolve().then(()=>Ib(b)))}
function Ib(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.hb());m(b,"fxstate",{fxstate:a});b.Xc=!1}
async function vb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await ib(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.Ya[0]=f[0],b.Ya[1]=f[1],b.Ya[2]=f[2],f=d.orient,b.Xa[0]=f[0],b.Xa[1]=f[1],b.Xa[2]=f[2],e.setPosition(...b.Ya),e.setOrientation(...b.Xa),b.sa[0]=d.cia,b.sa[1]=d.coa,b.sa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.qa=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),kb(b,d));c.Play(k,l,p,0);a.isPlaying||c.lb();c.Ic(a)}}}function Ab(b){console.error("[Audio] Offline rendering error: ",b)}
self.fb=class extends self.rc{constructor(b){super(b,"audio");this.Sa=this.g=null;this.Tb=this.Uc=!1;this.za=()=>{if(!this.Uc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Tb&&(this.Uc=!0,window.removeEventListener("pointerup",this.za,!0),window.removeEventListener("touchend",this.za,!0),window.removeEventListener("click",this.za,!0),window.removeEventListener("keydown",
this.za,!0),this.Tb=!1)}};this.ia=[];this.H=[];this.R=null;this.Yd=[];this.$d=new Set;this.Zd=-1;this.Eb=new Map;this.Zb=1;this.wa=!1;this.kd=0;this.jc=1;this.Rc=0;this.be="HRTF";this.Nd="inverse";this.ce=600;this.ae=1E4;this.ee=1;this.$=[0,0,0];this.ca=[0,0,-1,0,1,0];this.Td=this.dc=!1;this.he=this.m.Ge();this.ja=new Map;this.Qa=new Set;this.Ud=this.Xc=!1;this.ad="";this.Ia=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ia&&this.Ia.disconnect();this.ad=c.toLowerCase();this.Ia=this.g.createMediaStreamSource(a);
this.Ia.connect(Db(this,this.ad))};this.Sb=null;self.C3Audio_GetOutputStream=()=>{this.Sb||(this.Sb=this.g.createMediaStreamDestination(),this.Sa.connect(this.Sb));return this.Sb.stream};self.C3Audio_DOMInterface=this;ba(this,[["create-audio-context",a=>db(this,a)],["play",a=>gb(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Ca()}],["stop-all",()=>{for(const a of this.H)a.Ca()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.lb():d.Lb();S(this)}],["set-volume",
a=>{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>lb(this,a)],["set-master-volume",a=>{this.Zb=a.vol;this.Sa.gain.value=this.Zb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Jb(d,a)}],["set-silent",a=>{this.wa=a.isSilent;this.m.Nb(this.wa);for(const c of this.H)c.Qb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.zc(a)}],["set-playback-rate",a=>nb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),kb(d,a)}],["seek",a=>ob(this,a)],["preload",a=>pb(this,a)],["unload",a=>qb(this,a)],["unload-all",()=>{for(const a of this.ia)a.j();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Ac(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>rb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ja.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);tb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ja.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ja.delete(a);sb(this,a)}}],["tick",a=>{this.jc=a.timeScale;this.Rc=a.gameTime;this.Zd=a.tickCount;if(0!==this.kd)for(var c of this.H)c.Ea();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ca[0]!==
c[0]||this.ca[1]!==c[1]||this.ca[2]!==c[2]||this.ca[3]!==c[3]||this.ca[4]!==c[4]||this.ca[5]!==c[5])){for(let d=0;6>d;++d)this.ca[d]=c[d];this.g.listener.setOrientation(...this.ca)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.qa===a&&jb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>ub(this,a)],["offline-render-audio",a=>zb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Sa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Kb(){return this.wa}Da(b){this.m.Da(b)}Na(b){this.m.Na(b)}Oa(){for(var b of this.Qa)b.Oa();
b=this.g.currentTime;for(var a of this.H)a.Oa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.hb());m(this,"state",{tickCount:this.Zd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Qa].map(c=>({tag:c.hd,index:c.Vd,peak:c.Za,rms:c.de,binCount:c.l.frequencyBinCount,freqBins:c.Sd}))});0===a.length&&0===this.Qa.size&&this.Ub&&(this.m.Gd(this.ie),this.Ub=!1)}static Le(b){return b*cb}static vd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Je(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.Mb.nc(self.fb);"use strict";function Bb(b){b.Xb||(b.Xb=b.Hc());return b.Xb}self.rd=class{constructor(b,a,c,d,e){this.u=b;this.pf=a;this.Ja=c;this.T=d;this.lf=e;this.Nc="";this.Xb=null}j(){this.Xb=this.u=null}Hc(){}V(){return this.u.V()}vc(){return this.pf}ib(){return this.Ja}tc(){return this.T}Ba(){return this.lf}fa(){}};"use strict";
self.ye=class extends self.rd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Nc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.zb=this.Ab=null;this.L.addEventListener("canplaythrough",()=>!0);this.Db=this.V().createGain();this.Cb=null;this.L.addEventListener("canplay",()=>{this.Ab&&(this.Ab(),this.zb=this.Ab=null);!this.Cb&&this.L&&(this.Cb=this.V().createMediaElementSource(this.L),this.Cb.connect(this.Db))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ja}' error: `,f);this.zb&&(this.zb(f),this.zb=this.Ab=null)})}j(){Gb(this.u,this);this.Db.disconnect();this.Db=null;this.Cb.disconnect();this.Cb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Hc(){return new Promise((b,a)=>{this.Ab=b;this.zb=a;this.L.src=this.Ja})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Kb(b){if(b.Fa)return b.Fa;var a=b.u.m;if("cordova"===a.A&&a.xd(b.Ja)&&a.Vb)b.Fa=await a.Jb(b.Ja);else{a=await fetch(b.Ja);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Fa=await a.arrayBuffer()}}async function Lb(b){if(b.ha)return b.ha;b.ha=await Fb(b.u,b.Fa,b.nf);b.Fa=null}
self.Ae=class extends self.rd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Nc="webaudio";this.ha=this.Fa=null;this.nf=!!f}j(){Gb(this.u,this);this.ha=this.Fa=null;super.j()}async Hc(){try{await Kb(this),await Lb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ja}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Nb=0;
function P(b,a){a=!!a;b.wb!==a&&(b.wb=a,b.wb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.be,b.F.distanceModel=b.u.Nd,b.F.refDistance=b.u.ce,b.F.maxDistance=b.u.ae,b.F.rolloffFactor=b.u.ee),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function Q(b,a){a=!!a;b.Wb!==a&&(b.Wb=a,b.Wb?(P(b,!1),b.da=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.da),b.da.connect(b.ea())):(b.da.disconnect(),b.da=null,b.G.disconnect(),b.G.connect(b.ea())))}function kb(b,a){b.Wb&&b.gd!==a&&(b.da.pan.value=a,b.gd=a)}function T(b,a){b.Ka=a;b.G.gain.cancelScheduledValues(0);b.Ua=-1;b.G.gain.value=b.wc()}function Jb(b,a){a=!!a;b.va!==a&&(b.va=a,b.Qb())}
function jb(b,a,c,d,e){if(b.wb){var f=b.Ya,g=b.Xa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.Yc?b.u.Rc:performance.now()/1E3}
self.sd=class{constructor(b,a,c){this.u=b;this.P=a;this.na=c;this.Rb=Nb++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.wb=!1;this.Ya=[0,0,0];this.Xa=[0,0,0];this.sa=[0,0,0];this.da=null;this.Wb=!1;this.gd=0;this.I=!0;this.Y=this.ta=this.J=!1;this.Ka=1;this.va=!1;this.la=1;b=this.u.kd;this.Yc=1===b&&!this.Ba()||2===b;this.Ua=this.qa=-1;this.ge=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.da&&(this.da.disconnect(),this.da=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ea(){return Db(this.u,0<this.na.length?this.na[0]:"")}vc(){return this.P.vc()}ib(){return this.P.ib()}tc(){return this.P.tc()}Ba(){return this.P.Ba()}O(){}oc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}La(){}fa(){return this.P.fa()}Play(){}Ca(){}lb(){}Lb(){}Oa(b){-1!==this.Ua&&b>=this.Ua&&(this.Ua=-1,this.ge&&this.Ca(),Hb(this.u,"fade-ended",this.na,this.Rb))}wc(){const b=this.Ka;return isFinite(b)?b:0}Kb(){return this.u.Kb()}Qb(){}zc(){}Ea(){}yc(){}Ac(){}xc(){}hb(){var b=
this.Rb,a=this.na,c=this.fa(),d=-1===this.Ua?this.Ka:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ya,orient:this.Xa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.qa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.La(),playbackRate:this.la,uid:this.qa,bufferOriginalUrl:this.vc(),bufferUrl:"",bufferType:this.tc(),isMusic:this.Ba(),isLooping:this.Y,isMuted:this.va,resumePosition:this.xc(),pan:f,stereoPan:this.da?
this.gd:null}}Ic(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Ea());Jb(this,b.isMuted)}};"use strict";
self.ze=class extends self.sd{constructor(b,a,c){super(b,a,c);this.P.Db.connect(this.G);this.P.onended=()=>this.Jc()}j(){this.Ca();this.P.Db.disconnect();super.j()}W(){return this.P.W()}Jc(){this.I=!0;this.qa=-1;Hb(this.u,"ended",this.na,this.Rb)}O(){return this.W().ended}oc(){return this.I?!0:this.O()}La(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);this.va=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.ib()}' to position '${c}': `,e)}this.u.Da(d);this.J=this.I=!1;this.Y=b;this.la=1}Ca(){const b=this.W();b.paused||b.pause();this.u.Na(b);this.I=!0;this.J=!1;this.qa=-1}lb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.Na(b);this.J=!0}}Lb(){!this.J||this.I||this.O()||(this.u.Da(this.W()),this.J=!1)}Qb(){this.W().muted=this.va||this.Kb()}zc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ea(){let b=this.la;this.Yc&&(b*=this.u.jc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}yc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}xc(){return this.La()}Ac(b){b?this.IsPlaying()?(this.W().pause(),this.ta=!0):this.ta=!1:this.ta&&(this.u.Da(this.W()),this.ta=!1)}};"use strict";
function V(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.ob=null}
self.Be=class extends self.sd{constructor(b,a,c){super(b,a,c);this.s=null;this.ac=d=>this.Jc(d);this.Tc=!0;this.ob=null;this.S=this.cc=this.ec=0;this.cd=1}j(){this.Ca();V(this);this.ac=null;super.j()}Jc(b){this.J||this.ta||b.target!==this.ob||(this.I=this.Tc=!0,this.qa=-1,V(this),Hb(this.u,"ended",this.na,this.Rb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Tc}oc(){return!this.s||this.I?!0:this.O()}La(){let b;b=this.J?this.S:this.cc+(U(this)-this.ec)*this.la;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.va=!1;this.cd=1;T(this,a);V(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ha;this.s.connect(this.G);this.ob=this.s;this.s.onended=this.ac;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Tc=!1;this.Y=b;this.la=1;this.ec=U(this);this.cc=c}Ca(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.qa=-1}lb(){this.J||this.I||this.O()||(this.S=this.La(),this.Y&&(this.S%=this.fa()),this.J=!0,this.s.stop(0))}Lb(){!this.J||this.I||this.O()||(V(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.ob=this.s,this.s.onended=this.ac,this.s.loop=this.Y,T(this,this.Ka),this.Ea(),this.s.start(0,this.S),this.ec=U(this),this.cc=this.S,this.J=!1)}wc(){return super.wc()*this.cd}Qb(){this.cd=this.va||this.Kb()?0:1;T(this,this.Ka)}zc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ea(){let b=this.la;this.Yc&&(b*=this.u.jc);this.s&&(this.s.playbackRate.value=b)}yc(b){this.I||this.O()||(this.J?this.S=b:(this.lb(),
this.S=b,this.Lb()))}xc(){return this.S}Ac(b){b?this.IsPlaying()?(this.ta=!0,this.S=this.La(),this.Y&&(this.S%=this.fa()),this.s.stop(0)):this.ta=!1:this.ta&&(V(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.ob=this.s,this.s.onended=this.ac,this.s.loop=this.Y,T(this,this.Ka),this.Ea(),this.s.start(0,this.S),this.ec=U(this),this.cc=this.S,this.ta=!1)}Ic(b){super.Ic(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.V();this.Vd=-1;this.T=this.hd="";this.o=null}j(){this.g=null}N(){}U(){}hb(){return{type:this.T,tag:this.hd,params:this.o}}}
self.re=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.v=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}j(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,X(this,this.D.gain,a,c,d)}}};
self.pe=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.Bb=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.sb=W(this);this.sb.gain.value=c;this.v.connect(this.Bb);this.v.connect(this.h);this.Bb.connect(this.i);this.Bb.connect(this.X);this.X.connect(this.sb);this.sb.connect(this.Bb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.Bb.disconnect();
this.X.disconnect();this.sb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.fb.vd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);X(this,this.sb.gain,e(a),c,d);break;case 5:this.o[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.oe=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Md=this.Ld="";this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.rb=this.g.createConvolver();this.rb.normalize=c;this.rb.buffer=a;this.v.connect(this.rb);this.v.connect(this.h);this.rb.connect(this.i)}j(){this.v.disconnect();this.rb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}hb(){const b=super.hb();b.bufferOriginalUrl=this.Ld;b.bufferUrl="";b.bufferType=this.Md;return b}};
self.se=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.v=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.ub=W(this);this.ub.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=W(this);this.K.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.ub);this.ub.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.ub.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;X(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;X(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,X(this,this.ub.gain,a/100,c,d)}}};
self.ue=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.v=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=W(this);this.K.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;X(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,X(this,this.C.frequency,a,c,d)}}};self.te=class extends Z{constructor(b,a){super(b);this.T="gain";this.o=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.fb.vd;switch(b){case 4:this.o[0]=e(a),X(this,this.l.gain,e(a),c,d)}}};
self.we=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,X(this,this.l.pan,a,c,d)}}};
self.xe=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.l=W(this);this.l.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=W(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.l.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;X(this,this.l.gain,1-a/2,c,d);X(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.ve=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.v=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.Gb=W(this);this.Gb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Gb.gain);this.C.start(0);this.v.connect(this.Gb);this.v.connect(this.h);this.Gb.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Gb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.qe=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.v=W(this);this.hc=W(this);this.fc=W(this);b=d;.01>b&&(b=.01);this.hc.gain.value=b;this.fc.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.kc=this.g.createWaveShaper();this.Oc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Oc[32768+e]=f,this.Oc[32768-
e-1]=-f;this.kc.curve=this.Oc;this.v.connect(this.hc);this.v.connect(this.h);this.hc.connect(this.kc);this.kc.connect(this.fc);this.fc.connect(this.i)}j(){this.v.disconnect();this.hc.disconnect();this.kc.disconnect();this.fc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.ne=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.me=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Sd=new Float32Array(this.l.frequencyBinCount);this.fe=new Uint8Array(a);this.de=this.Za=0;b=this.u;b.Qa.add(this);S(b)}j(){this.u.Qa.delete(this);this.l.disconnect();super.j()}Oa(){this.l.getFloatFrequencyData(this.Sd);this.l.getByteTimeDomainData(this.fe);const b=this.l.fftSize;let a=this.Za=0;for(var c=0;c<b;++c){let d=(this.fe[c]-
128)/128;0>d&&(d=-d);this.Za<d&&(this.Za=d);a+=d*d}c=self.fb.Je;this.Za=c(this.Za);this.de=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
